services:
  postgres:
    image: postgres:15.4
    container_name: help-fridge-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - '5432:5432'
    volumes:
      - help-fridge-dev-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  help-fridge-dev-data:
